### ISSUE TITLE
No favicon 

### ISSUE THREAD

**Issue by msweet168** [ComputerScienceHouse/CSHMembersPortal#70] opened 2016-11-22 02:39 UTC
Hello!

When I pin the members.csh.rit.edu website to my home screen, the icon is either blank or just a random screenshot. This is because the website does not have a favicon. It would be great if a favicon could be added. I attached a favicon image to this post. 

Thanks! 
![final csh icon](https://cloud.githubusercontent.com/assets/11968883/20508911/f3988d20-b032-11e6-9ad2-fc09c1ff071f.png)

**Comment by mbillow** [comment] 2016-12-03 20:54
Duplicate of #37 
Updates will be tracked there.

**Closed by mbillow** 2016-12-03 20:54 UTC
